### ISSUE TITLE
Nedostaje mogućnost dodavanja auth tokena preko Swagger-a

### ISSUE THREAD

**Issue by sbuljat** [OdinZD/RWA-Project-1#1]
API metode koje zahtijevaju autorizaciju moraju imati autorizaciju kako bi se mogao dodati token kojeg dobijemo pri **signin** API metodi.

**Comment by OdinZD** [comment]
Dodao sam mogućnost provjere Auth tokena preko swagger-a za usera. Nisam jos na Ti sa githubom pa neznam dali ovdje moram staviti sliku toga sto sam napravio :)
