### ISSUE TITLE
Koja je namjena "admin" polja pri registraciji korisnika?

### ISSUE THREAD

**Issue by sbuljat** [OdinZD/RWA-Project-1#3]

**Comment by sbuljat** [comment]
Zar to nije sigurnosni rizik ako svatko sebe može proglasiti administratorom?

**Comment by OdinZD** [comment]
Prvotno je bilo samo radi lakseg rada u swaggeru pa je tako i ostalo. Ali slažem se to je loša praksa i to će se do finalnog projekta ispraviti tako da će se tim poljem moći manipulirati samo preko admin usera i zasebnog admin UI.

**Comment by sbuljat** [comment]
Zbog ovoga i nekoliko drugih sitnica koje nisu napravljene možemo Vam ponuditi 11 bodova od maksimalno 15 bodova, jeste zadovoljni s tim?

**Comment by OdinZD** [comment]
Jesam. Hvala

**Comment by sbuljat** [comment]
Dogovoreno.
